### ISSUE TITLE
Next errors ;-)

### ISSUE THREAD

**Issue by mdaehnert** [elyukai/optolith-client#11]
* Branch: feature/jaxt0r_up_and_running
* Info: Build comes further this time but stucks again. Maybe you have a few minutes to reproduce the error locally.

I started with
1. ```npm i``` - all ok
1. ```npm run bundle``` - unused imports errors etc.

Now the error:
```
D:\_\git\private\tdeheroes-code>npm run build

> optolyth@1.0.2 build D:\_\git\private\tdeheroes-code
> electron-builder --config -lw

electron-builder 19.46.6
Using electron-builder.json configuration file
No native production dependencies
Packaging for linux x64 using electron 2.0.2 to dist\linux-unpacked
Building tar.gz
No native production dependencies
Packaging for linux ia32 using electron 2.0.2 to dist\linux-ia32-unpacked
Building tar.gz
No native production dependencies
Packaging for win32 x64 using electron 2.0.2 to dist\win-unpacked
No native production dependencies
Packaging for win32 ia32 using electron 2.0.2 to dist\win-ia32-unpacked
Building nsis installer (x64 and ia32)
TypeError: "size" argument must be a number
    at Function.Buffer.allocUnsafe (buffer.js:253:3)
    at D:\_\git\private\tdeheroes-code\node_modules\app-package-builder\src\SevenZFile.ts:49:23
    at Generator.next (<anonymous>)
From previous event:
    at SevenZFile.readHeaders (D:\_\git\private\tdeheroes-code\node_modules\app-package-builder\out\SevenZFile.js:132:11)
    at D:\_\git\private\tdeheroes-code\node_modules\app-package-builder\src\SevenZFile.ts:45:31
    at Generator.next (<anonymous>)
From previous event:
    at SevenZFile.read (D:\_\git\private\tdeheroes-code\node_modules\app-package-builder\out\SevenZFile.js:92:11)
    at D:\_\git\private\tdeheroes-code\node_modules\app-package-builder\src\blockMap.ts:43:22
    at Generator.next (<anonymous>)
    at D:\_\git\private\tdeheroes-code\node_modules\graceful-fs\graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at createDifferentialPackage (D:\_\git\private\tdeheroes-code\node_modules\app-package-builder\out\blockMap.js:61:21)
    at D:\_\git\private\tdeheroes-code\node_modules\electron-builder-lib\src\targets\nsis\NsisTarget.ts:91:20
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at NsisTarget.buildAppPackage (D:\_\git\private\tdeheroes-code\node_modules\electron-builder-lib\out\targets\nsis\NsisTarget.js:190:11)
    at D:\_\git\private\tdeheroes-code\node_modules\electron-builder-lib\src\targets\nsis\nsisUtil.ts:32:28
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at D:\_\git\private\tdeheroes-code\node_modules\electron-builder-lib\src\targets\nsis\nsisUtil.ts:32:10
    at Generator.next (<anonymous>)
From previous event:
    at AppPackageHelper.packArch (D:\_\git\private\tdeheroes-code\node_modules\electron-builder-lib\out\targets\nsis\nsisUtil.js:92:11)
    at D:\_\git\private\tdeheroes-code\node_modules\electron-builder-lib\src\targets\nsis\NsisTarget.ts:177:51
    at Generator.next (<anonymous>)
From previous event:
    at default.map (D:\_\git\private\tdeheroes-code\node_modules\electron-builder-lib\out\targets\nsis\NsisTarget.js:287:37)
From previous event:
    at D:\_\git\private\tdeheroes-code\node_modules\electron-builder-lib\src\targets\nsis\NsisTarget.ts:176:29
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at NsisTarget.buildInstaller (D:\_\git\private\tdeheroes-code\node_modules\electron-builder-lib\out\targets\nsis\NsisTarget.js:337:11)
    at D:\_\git\private\tdeheroes-code\node_modules\electron-builder-lib\src\targets\nsis\NsisTarget.ts:102:18
    at Generator.next (<anonymous>)
From previous event:
    at NsisTarget.finishBuild (D:\_\git\private\tdeheroes-code\node_modules\electron-builder-lib\out\targets\nsis\NsisTarget.js:205:11)
    at D:\_\git\private\tdeheroes-code\node_modules\electron-builder-lib\src\packager.ts:338:36
From previous event:
    at Packager.doBuild (D:\_\git\private\tdeheroes-code\node_modules\electron-builder-lib\out\packager.js:396:11)
    at D:\_\git\private\tdeheroes-code\node_modules\electron-builder-lib\src\packager.ts:274:52
From previous event:
    at Packager._build (D:\_\git\private\tdeheroes-code\node_modules\electron-builder-lib\out\packager.js:340:11)
    at D:\_\git\private\tdeheroes-code\node_modules\electron-builder-lib\src\packager.ts:244:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (D:\_\git\private\tdeheroes-code\node_modules\electron-builder-lib\out\packager.js:300:11)
    at D:\_\git\private\tdeheroes-code\node_modules\electron-builder\src\builder.ts:287:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (D:\_\git\private\tdeheroes-code\node_modules\electron-builder\out\builder.js:61:21)
    at build (D:\_\git\private\tdeheroes-code\node_modules\electron-builder\src\builder.ts:257:10)
    at then (D:\_\git\private\tdeheroes-code\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (D:\_\git\private\tdeheroes-code\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at Object.runCommand (D:\_\git\private\tdeheroes-code\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (D:\_\git\private\tdeheroes-code\node_modules\yargs\yargs.js:1041:24)
    at Object.get [as argv] (D:\_\git\private\tdeheroes-code\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (D:\_\git\private\tdeheroes-code\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! optolyth@1.0.2 build: `electron-builder --config -lw`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the optolyth@1.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by SirunGameDev** [comment]
Is this issue still relevant?
