### ISSUE TITLE
Cannot add tradition of Nameless One because of exception

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#414]
**Describe the bug**
```
TypeError: fmap: missing instance of Functor
InactiveActivatable { cost = Just 13
                    , customCostDisabled = Nothing
                    , heroEntry = Nothing
                    , id = "SA_543"
                    , isAutomatic = False
                    , maxLevel = Just 3
                    , minLevel = Nothing
                    , name = "Macht der Namenlosen Klinge"
                    , selectOptions = Nothing
                    , wikiEntry = SpecialAbility { aeCost = Nothing
                                                 , apValue = Nothing
                                                 , apValueAppend = Nothing
                                                 , aspect = Nothing
                                                 , bindingCost = Nothing
                                                 , brew = Nothing
                                                 , category = "SPECIAL_ABILITIES"
                                                 , combatTechniques = Nothing
                                                 , cost = Just 13
                                                 , effect = Just "Für jede Stufe der Sonderfertigkeit erhält der Namenloser-Geweihte einen Bonus für den Opferdolch. Diese Boni sind kumulativ.\n\n- Stufe I: +1 TP\n- Stufe II: +1 AT\n- Stufe III: Wenn die Waffe SP verursacht, erleidet das Ziel 1 Stufe *Furcht*.\n- Stufe IV: +1 TP\n- Stufe V: +1 AT\n- Stufe VI: Wenn die Waffe SP verursacht, erleidet das Ziel 1 Stufe *Schmerz*.\n- Stufe VII: +1 TP\n- Stufe VIII: +1 AT\n- Stufe IX: Wenn die Waffe SP verursacht, erleidet das Ziel 1 Stufe *Furcht*.\n- Stufe X: +1 TP\n- Stufe XI: +1 AT\n- Stufe XII: Wenn die Waffe SP verursacht, erleidet das Ziel 1 Stufe *Schmerz*.\n- Stufe XIII: Wenn die Waffe SP verursacht, erleidet das Ziel den Status *Bewegungsunfähig*.\n"
                                                 , errata = []
                                                 , extended = Nothing
                                                 , gr = 23
                                                 , id = "SA_543"
                                                 , input = Nothing
                                                 , max = Just 1
                                                 , name = "Macht der Namenlosen Klinge"
                                                 , nameInWiki = Nothing
                                                 , penalty = Nothing
                                                 , prerequisites = Map ( 1 = [RequireActivatable { active = True, id = "SA_693", sid = Nothing, sid2 = Nothing, tier = Nothing }]
                                                                       , 13 = [RequireActivatable { active = True, id = "SA_563", sid = Nothing, sid2 = Nothing, tier = Just (3) }]
                                                                       , 8 = [RequireActivatable { active = True, id = "SA_563", sid = Nothing, sid2 = Nothing, tier = Just (2) }]
                                                                       , 4 = [RequireActivatable { active = True, id = "SA_563", sid = Nothing, sid2 = Nothing, tier = Just (1) }]
                                                                   )
                                                 , prerequisitesText = Just "Stufe I: Sonderfertigkeit Tradition (Namenloser Kult); jede andere Stufe benötigt die Vorgängerstufe Macht der Namenlosen Klinge als Voraussetzung und zusätzlich weitere Grade der Namenlosen Weihe: ab Stufe 4 den zweiten Grad, ab Stufe 8 den dritten Grad und ab Stufe 13 den vierten Grad."
                                                 , prerequisitesTextEnd = Nothing
                                                 , prerequisitesTextIndex = Map ( 
                                                                            )
                                                 , prerequisitesTextStart = Nothing
                                                 , property = Nothing
                                                 , protectiveCircle = Nothing
                                                 , rules = Nothing
                                                 , select = Nothing
                                                 , src = [ SourceLink { id = "US25005"
                                                                      , page = 64 } ]
                                                 , subgr = Nothing
                                                 , tiers = Just 13
                                                 , volume = Nothing
                                                 , wardingCircle = Nothing } }
    at C:\Program Files\Optolith Insider\resources\app.asar\app\Data\Functor.js:75:11
    at C:\Program Files\Optolith Insider\resources\app.asar\app\Data\Functor.js:77:46
    at C:\Program Files\Optolith Insider\resources\app.asar\app\App\Utilities\Activatable\activatableInactiveUtils.js:327:59
    at C:\Program Files\Optolith Insider\resources\app.asar\app\Data\Functor.js:56:27
    at C:\Program Files\Optolith Insider\resources\app.asar\app\App\Utilities\pipe.js:8:51
    at Array.reduce (<anonymous>)
    at Object.exports.pipe_ (C:\Program Files\Optolith Insider\resources\app.asar\app\App\Utilities\pipe.js:8:34)
    at C:\Program Files\Optolith Insider\resources\app.asar\app\App\Utilities\Activatable\activatableInactiveUtils.js:320:23
    at Array.<anonymous> (C:\Program Files\Optolith Insider\resources\app.asar\app\App\Selectors\inactiveActivatablesSelectors.js:37:243)
    at C:\Program Files\Optolith Insider\resources\app.asar\app\App\Utilities\pipe.js:7:51

COMPONENT STACK

    in ConnectFunction (created by Router)
    in Router (created by App)
    in section (created by App)
    in div (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction
    in Provider
```

SA Namenlose Klinge is missing, too. 

**To Reproduce**
Try to add SA Tradition (Nameless One)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/11094577/75296415-676a1700-582d-11ea-84da-9f15a526e4b0.png)

**Environment (please complete the following information):**

- OS: Windows 10
- Version: 1.3.0-alpha.7

**Comment by elyukai** [comment]
> wenn ich im editor die tradition entferne gehts wieder wie gewollt

> bzw die SF macht der namenlosen klinge kann nur mit der Tradition gewählt werden
